<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-- Select Category --' => '',
    '--- Select Parent ---' => '',
    'Address' => '',
    'Are you sure you want to delete this item?' => '',
    'Belongto' => '',
    'Billing Type' => '',
    'Budget' => '',
    'Business Register' => '',
    'Categories' => '',
    'Category ID' => '',
    'Category Registers' => '',
    'Certify' => '',
    'City' => '',
    'Comment' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Customer ID' => '',
    'Customer Type' => '',
    'Customers' => '',
    'Data Msg' => '',
    'Date' => '',
    'Delete' => '',
    'Delivery Address' => '',
    'Delivery Date' => '',
    'Delivery Type' => '',
    'Description' => '',
    'Disable' => '',
    'Due Date' => '',
    'Email' => '',
    'Enable' => '',
    'Full Name' => '',
    'ID' => '',
    'Invite ID' => '',
    'Invite Type' => '',
    'Invites' => '',
    'Level' => '',
    'Lft' => '',
    'Mobile' => '',
    'Name' => '',
    'Order Date' => '',
    'Order Description' => '',
    'Order ID' => '',
    'Order Name' => '',
    'Order Status' => '',
    'Order Type' => '',
    'Orders' => '',
    'Password' => '',
    'Phone' => '',
    'Po Status' => '',
    'Pos' => '',
    'Price' => '',
    'Product Image' => '',
    'Quantity' => '',
    'Rating Type' => '',
    'Ratings' => '',
    'Reset' => '',
    'Response Data' => '',
    'Response Date' => '',
    'Response Type' => '',
    'Responses' => '',
    'Rfp Attach' => '',
    'Rgt' => '',
    'Root' => '',
    'Score' => '',
    'Search' => '',
    'Status' => '',
    'Supplier ID' => '',
    'Supplier Type' => '',
    'Suppliers' => '',
    'Unit' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Username' => '',
];
